language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

matrix:
  - php: 5.4
  - php: 5.5
  - php: 5.6
    before_install:
        - pecl install pthreads-2.0.10
        - pecl install xdebug
        - phpenv rehash
  - php: 7.0
    before_install: 
      - pecl install pthreads

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
