language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_install:
  - pecl install pthreads
  - pecl install xdebug
  - phpenv rehash

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
